#!/bin/sh

/system/raminit

# Copy root folders in the new mountpoint.
for dir in */; do
    case $dir in
    dev/)
        # skip
        ;;
    proc/)
        # skip
        ;;
    sys/)
        # skip
        ;;
    mnt/)
        # skip
        ;;
    tmp/)
        # skip
        ;;
    *)
        cp -a $dir /mnt
        ;;
    esac
done

printf "Exiting initramfs\n"

# exec switch_root /mnt /system/init
exec switch_root /mnt /sbin/init
