[[sources]]
name = "linux"
url = "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.8.6.tar.xz"
target = "linux.tar.xz"
version = "6.8.6"
hash = "sha256:9e723232d603ab45ebf043c34714c48f277ab195c29abcb8472f2a4c3a5a1995"

[[sources]]
name = "busybox"
url = "http://sources.buildroot.net/busybox/busybox-1.36.1.tar.bz2"
target = "busybox.tar.bz2"
version = "1.36.1"
hash = "dfdfc1b9aa41d5134e087d904c0a5f6958825f0e94db1d2cb5ea93088247c886"

[[sources]]
name = "dash"
url = "https://git.kernel.org/pub/scm/utils/dash/dash.git/snapshot/dash-0.5.12.tar.gz"
target = "dash.tar.gz"
version = "0.5.12"
hash = "f38a283332d2b34058112fe4f06d2148f2318610e08ad23bd70c2e206db505eb"

[[sources]]
name = "limine"
url = "https://github.com/limine-bootloader/limine/releases/download/v7.3.1/limine-7.3.1.tar.bz2"
target = "limine.tar.bz2"
version = "7.3.1"
hash = "f4d2df7bb35ba650b2e1d124249911bce6dae88dbe70fec83b91e2f0741245d0"

[[sources]]
name = "llvm"
url = "https://cdn.kernel.org/pub/tools/llvm/files/llvm-18.1.3-x86_64.tar.xz"
target = "llvm.tar.xz"
version = "18.1.3"
hash = "sha256:0c73a4c6f26f27a173cd4b9edcd6b83b2958dc420afd8588937c0db686160409"

[[sources]]
name = "mesa"
url = "https://archive.mesa3d.org/mesa-24.0.2.tar.xz"
target = "mesa.tar.xz"
version = "24.0.2"
hash = "dc461fa04c83b35eec845f3f1e9837acb904a56f55bb77e8d1dbff97a87f4dda"
