[[sources]]
name = "linux"
url = "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.9.tar.xz"
target = "linux.tar.xz"
version = "6.9"
hash = "sha256:24fa01fb989c7a3e28453f117799168713766e119c5381dac30115f18f268149"

[[sources]]
name = "busybox"
url = "http://sources.buildroot.net/busybox/busybox-1.36.1.tar.bz2"
target = "busybox.tar.bz2"
version = "1.36.1"
hash = "dfdfc1b9aa41d5134e087d904c0a5f6958825f0e94db1d2cb5ea93088247c886"

[[sources]]
name = "dash"
url = "https://git.kernel.org/pub/scm/utils/dash/dash.git/snapshot/dash-0.5.12.tar.gz"
target = "dash.tar.gz"
version = "0.5.12"
hash = "f38a283332d2b34058112fe4f06d2148f2318610e08ad23bd70c2e206db505eb"

[[sources]]
name = "limine"
url = "https://github.com/limine-bootloader/limine/releases/download/v7.5.1/limine-7.5.1.tar.bz2"
target = "limine.tar.bz2"
version = "7.5.1"
hash = "4a262b88f45392f8dffbee948fcffeec167b25c4182c992b84fa1c79094dea11"

[[sources]]
name = "llvm"
url = "https://cdn.kernel.org/pub/tools/llvm/files/llvm-18.1.5-x86_64.tar.xz"
target = "llvm.tar.xz"
version = "18.1.5"
hash = "sha256:dc1bf4ea80503665f59651e1d76a98aa047d5c54ad354ec398c4c20e7d74711c"

[[sources]]
name = "mesa"
url = "https://archive.mesa3d.org/mesa-24.0.2.tar.xz"
target = "mesa.tar.xz"
version = "24.0.2"
hash = "dc461fa04c83b35eec845f3f1e9837acb904a56f55bb77e8d1dbff97a87f4dda"
