[[sources]]
name = "linux"
url = "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.10.6.tar.xz"
target = "linux.tar.xz"
version = "6.10.6"
hash = "sha256:e0d50d5b74f8599375660e79f187af7493864dba5ff6671b14983376a070b3d1"

[[sources]]
name = "busybox"
url = "http://sources.buildroot.net/busybox/busybox-1.36.1.tar.bz2"
target = "busybox.tar.bz2"
version = "1.36.1"
hash = "dfdfc1b9aa41d5134e087d904c0a5f6958825f0e94db1d2cb5ea93088247c886"

[[sources]]
name = "dash"
url = "https://git.kernel.org/pub/scm/utils/dash/dash.git/snapshot/dash-0.5.12.tar.gz"
target = "dash.tar.gz"
version = "0.5.12"
hash = "f38a283332d2b34058112fe4f06d2148f2318610e08ad23bd70c2e206db505eb"

[[sources]]
name = "limine"
url = "https://github.com/limine-bootloader/limine/releases/download/v8.0.5/limine-8.0.5.tar.xz"
target = "limine.tar.xz"
version = "8.0.5"
hash = "6278c78fa34bb177e1ecc3d713cf69b9b2f800133b1077d850e444c4223b8004"

[[sources]]
name = "llvm"
url = "https://cdn.kernel.org/pub/tools/llvm/files/llvm-18.1.8-x86_64.tar.xz"
target = "llvm.tar.xz"
version = "18.1.8"
hash = "sha256:857d351a600243f7d79fd6dc40187a10a5e91d2fafbb580424707026a6f98c9d"

[[sources]]
name = "mesa"
url = "https://archive.mesa3d.org/mesa-24.0.2.tar.xz"
target = "mesa.tar.xz"
version = "24.0.2"
hash = "dc461fa04c83b35eec845f3f1e9837acb904a56f55bb77e8d1dbff97a87f4dda"
