[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-unknown-linux-none]
rustflags = [
    "-C",
    "target-feature=+crt-static",
    "-C",
    "relocation-model=static",
    "-C",
    "link-arg=-nostartfiles",
    "-C",
    "linker=clang",
    "-C",
    "link-arg=-fuse-ld=lld",
]
