name: ci
on: [push, pull_request]

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Install dependencies
        run: |
          pacman --noconfirm -Syu && pacman --needed --noconfirm -S \
          base-devel git autoconf automake nasm curl mtools llvm clang lld just rustup bc libarchive erofs-utils python f2fs-tools qemu-base

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install sugo
        run: cargo install --git https://github.com/morr0ne/sugo.git

      - name: Add sugo to path
        run: cp ~/.cargo/bin/sugo /usr/local/bin

      - name: Build image
        run: just

      - name: Build qemu disk
        run: just create-disk

      # - name: Upload image
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: woven-${{ github.sha }}.iso
      #     path: woven.iso
      #     if-no-files-found: error
      #     retention-days: 1
