name: ci
on: [push, pull_request]

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Install dependencies
        run: |
          pacman --noconfirm -Syu && pacman --needed --noconfirm -S \
          base-devel git autoconf automake nasm curl mtools llvm clang lld just rye rustup

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image
        run: just
